---
name: Check yaml syntax

on:
  push:
    paths:
      - '**.yaml'
      - '**.yml'
      - '.github/workflows/syntax-yaml.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
      - '.github/workflows/syntax-yaml.yml'

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip3 install yamllint
      - run: yamllint --config-file .github/yamllint.yml .
